#!/usr/bin/env bash
#############################################################################################
##程序描述：模拟jstorm
##实现功能：
##运行周期：
##创建作者：
##创建日期：2021-03-19
#############################################################################################

###############################
##参数设置
###############################
#路径
FWDIR="$(cd `dirname $0`;pwd)"
#引入工具类
TOOL_PATH=${FWDIR}
. $TOOL_PATH/tool.func

###############################
##传入的参数判断与设置
###############################
if [[ $# -lt 1 ]]; then
  fun_log 2 "there is no enough args, you need input(list|restart|...)";
  exit 1;
fi

case $1 in
        "list" )
                echo "      \"name\": \"test1\",";
                echo "      \"id\": \"test1-100\","
                echo "      \"name\": \"location_merge\",";
                echo "      \"id\": \"location_merge-101\",";
        ;;
        "restart" )
                echo "restart ${2}"
        ;;
        * )
                echo "no defined"
        ;;
esac